version: '3.9'

services:
  mongodb:
    container_name: vueschool-mongodb
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume:
